### PR TITLE
bump version to use optimize-paths 1.2.2

### PR DESCRIPTION
**Pull request by MAKIO135**
Major improvement on plot time 🤖✏️💨

Before:

After:

### CODE REVIEW

**Comment by MAKIO135** [comment]
Hello 👋
Any issue with this PR?

**Comment by TDMW** [comment]
Would love to see this PR be accepted too!

**Comment by ianstormtaylor** [comment]
Hey @nornagon, if you happen to get time it would be amazing to get this released in a new version—really looking forward to it cutting down on plot time. Thank you!

**Review by nornagon — APPROVED** [review]

**Comment by nornagon** [comment]
Released in 0.15.0.

**Comment by ianstormtaylor** [comment]
@nornagon Thank you!!

**Pull request merged**
