### PR TITLE
Pi-Zero: OTG configuration

### PR DESCRIPTION
**Pull request by osresearch**
Document how to setup the Pi Zero with a special "OTG" cable to power the Pi from the AxiDraw's servo regulator and connect the Pi's Micro USB to the AxiDraw's Micro USB.

### CODE REVIEW

**Comment by jedahan** [comment]
Did you modify the default cmdline.txt as well to include `modules-load=dwc2` or is that unnecessary?

**Comment by jedahan** [comment]
I was able to replicate this (though my cable is a bit less pretty) - thanks for the info!

**Comment by osresearch** [comment]
@nornagon Any thoughts on merging this documentation fix for other Pi 0 users wire up their axidraws?

**Review by nornagon — APPROVED** [review]
I was thinking this might be better in a separate doc file, but this is fine for now.

**Comment by superhighfives** [comment]
Would anyone be up for writing a brief overview of how to do this? Just trying to understand the relationship between the two usb cables and the headers, and how to splice that together.

For example, would something like this work, or would the fact that only one is powered be an issue? Would it require two data + power friendly micro-usb cables to be spliced together?

image

Actually, to simplify the question, I should probably just ask: what is happening in this bit of the image?

image

**Comment by osresearch** [comment]
I don't think that cable would work since there are no USB-A connectors available and the power-only connector doesn't have data lines.

My setup was made from two USB micro cables; If you have an old EBB with a Mini plug, then you can make a custom Mini-to-Micro cable.  At the minimum you need to cut the micro ends off and strip the wires back. connect red to red, black to black, white to white, and green to green so that you have a straight-through double ended cable. If you also want to power the Pi from it, the red and black need addition wires with 0.1" headers on them to take +5V from the Axidraw's servo rail. The servo headers have three pins, black for ground, red for power, and white for data -- you only need to connect to the black and red.

**Pull request merged**
