### PR TITLE
Migrate from webpack to esbuild

### PR DESCRIPTION
**Pull request by jedahan**
This makes saxi buildable on a raspberry pi zero (webpack OOMs even with 1.5Gb of memory).

This also enables live-reload during development.

In general, there should be a speed increase but I am not sure how much that matters.

### CODE REVIEW

**Comment by alexrudd2** [comment]
@jedahan This PR includes all the changes in my fork that should perhaps be landed separately (not sure what @nornagon thinks?).  You may want to rebase first.

**Comment by alexrudd2** [comment]
I can confirm that the proposed switch to esuild works for me (on an M1 Mac).  Quite fast, too.

**Comment by jedahan** [comment]
didnt mean to open this as nornagon seems unmaintained i'm happy if its just in your fork

**Comment by nornagon** [comment]
Hey, I'm here, I just have a 3 month old child. Feel free to keep this open.

**Comment by jedahan** [comment]
Yooo congrats! I'll rebase and reopen shortly

**Pull request closed without merging**
