### PR TITLE
Support brushless servo upgrade

### LINKED ISSUE #136: brushless
Hi,

Is there a way to use Saxi with the brushless kit : 
https://shop.evilmadscientist.com/productsmenu/else?id=56
By default, it's not look OK :(

### PR DESCRIPTION
**Pull request by alexrudd2**
Closes #136 
This intends to add support for the brushless servo [upgrade kit](https://shop.evilmadscientist.com/productsmenu/else?id=56).

See:
https://github.com/theophoric/saxi/commit/467c814999bd2886a539b2889b934d64369d3a3b
https://github.com/evil-mad/axidraw/compare/v3.7.2...v3.8.0
https://github.com/nornagon/saxi/issues/136#issuecomment-1589722896

I think this should be a configurable option rather than a permanent change.  The same software should be able to support both motor options.  Therefore, I've attempted a lower-level refactor.  I don't know the best way to expose a configuration option.

@nornagon  can you help me out here?

### CODE REVIEW

**Comment by alexrudd2** [comment]
This compiles and runs on real hardware (non-brushless), running the old/current code.

**Comment by nornagon** [comment]
Yeah, the Right Way to do this is to add device configuration support to saxi, which it sort-of-kind-of has the beginnings of (you found it with the ToolingProfile and Device interfaces), but this has never been exposed in the UI (either web or CLI), and hasn't really been well developed in the code either.

My suggestion for the fastest way to get something like this landed would be to add support for alternative device configurations to the CLI only, i.e. the plot command mode and the server mode, as a command-line flag. e.g. `saxi --device=AxidrawBrushless` would put the server in the mood to command pin 5 instead of pin 4, etc. This circumvents needing to figure out where in the UI that sort of configuration should go, which can come later.

**Comment by jedahan** [comment]
I wonder if we can detect the model through ebb api...

**Comment by alexrudd2** [comment]
> I'd love to merge something like this, but it's still in a pretty messy state, including several refactors. Perhaps we could break out the unrelated refactors into separate PRs, then build the brushless support on top?

Yep, we've already got brushless support working in the fork at https://github.com/alexrudd2/saxi/pull/114 but this was an earlier branch.

Since things were starting to diverge, I created a project to track changes to submit upstream (i.e. to you).  https://github.com/users/alexrudd2/projects/1. I'll have to go back and rebase now that several PRs have been merged in.

**Comment by alexrudd2** [comment]
Closing in favor of https://github.com/nornagon/saxi/pull/197

**Pull request closed without merging**
