### PR TITLE
ci: Remove CircleCI and update Node versions

### PR DESCRIPTION
**Pull request by alexrudd2**
Closes https://github.com/nornagon/saxi/issues/140.

I have forced an update of the transitive dependency `nan` in `package-lock.json`, but avoided listing it as a direct dependency in `package.json`.  Along with updating `webpack` to v5, this _would_ make the CI green (https://github.com/alexrudd2/saxi/commit/725f0ed125a29e1c5260609eb43fd9e3813f94ee)...

... if  https://github.com/nornagon/saxi/issues/139 is fixed.  So I expect this PR to fail for the time being.

### CODE REVIEW

**Comment by alexrudd2** [comment]
> While removing CI _does_ technically result in CI not failing, I'd prefer CI to get closer to passing instead 😅

Oh, sorry I was unclear.  This removes CircleCI but retains/updates GitHub Actions.  I'm assuming there was no need for both.

**Comment by nornagon** [comment]
Ah, right, yes that makes sense. Thanks!

I've regenerated package-lock.json because as a rule I don't merge package-lock.json changes from untrusted folks for security reasons.

**Comment by alexrudd2** [comment]
> I've regenerated package-lock.json because as a rule I don't merge package-lock.json changes from untrusted folks for security reasons.

OK, fine with me.  It actually might save a bit of trouble later in with broken dependencies.


Actually, I've now managed to update ALL the dependencies and fix the CI in my fork: https://github.com/alexrudd2/saxi. (It was a pretty painful introduction to TypeScript 😆 ).  

How would you prefer I upstream things?  (Note I _did_ revert 593c451e8ba252b1e85f27c373df8c2aa621b723, as did other people).

**Comment by nornagon** [comment]
I don't want to accept a revert of 593c451 into this repository. I'm happy to review other reasonable changes though!

**Comment by alexrudd2** [comment]
> I don't want to accept a revert of [593c451](https://github.com/nornagon/saxi/commit/593c451e8ba252b1e85f27c373df8c2aa621b723) into this repository. I'm happy to review other reasonable changes though!

OK.  I'll gently ask you to reconsider.   It does break the CI, apparently breaks some people's real hardware (https://github.com/nornagon/saxi/issues/131), and at least one other fork has also [reverted](9bcd2f7512ed2e4158695ddb03817e138522cd08).


In any case, I'll see what I can do to apply the fixes I've learned using my fork in manageable PRs.

Are you interested in setting up `renovatebot`?

**Comment by nornagon** [comment]
The CI breaking is not a fundamental problem with WebSerial support; it's certainly fixable. It's far from clear to me that #131 is a problem with WebSerial per se. If it is, I'd rather find and fix the issue than remove WebSerial support.

I have no idea what renovatebot is or why I'd want it, perhaps you could give a little more info?

**Comment by alexrudd2** [comment]
> The CI breaking is not a fundamental problem with WebSerial support; it's certainly fixable.

I was able to fix part of it (with a polyfill), but couldn't get it all the way.  I'll send a PR with the partial fix.

> It's far from clear to me that #131 is a problem with WebSerial per se. If it is, I'd rather find and fix the issue than remove WebSerial support.

I'll test on real hardware soon and let you know if I can reproduce.

> I have no idea what renovatebot is or why I'd want it, perhaps you could give a little more info?

[Renovatebot](https://www.mend.io/renovate/) is a more powerful Dependabot.  Here's an example PR - it groups similar updates together, and gives full changelogs: https://github.com/alexrudd2/saxi/pull/42.   I also set it up to automatically merge when the CI passes (with the revert, of course).  No affiliation, I'm just impressed.

**Comment by nornagon** [comment]
Eh, no thanks, I like that dependabot is built into github and requires very little thought from me. Mend.io seems like something that quite possibly won't exist in 5 years, which is already less than the lifetime of this project :)

**Pull request merged**
